[package]
name = "codi-linuxd"
publish = false
license = "MIT OR Apache-2.0"
readme = "/rust/README.md"
repository = "https://github.com/shymega/cosmo-codi-linux"
description = "Rust implementation of the CoDi interface for Linux"
categories = ["cover-display", "codi"]
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
keywords = ["cover-display", "codi"]
edition = "2018"

[[bin]]
name = "codi-linuxd"

[features]
default = []

[dependencies]
glib = "0.10.3"
serialport = "4.0.0"
futures = "0.3.13"
dbus = "0.9.2"
config = "0.10.1"
dbus-tokio = "0.7.3"
restruct_derive = "0.1.1"
restruct = "0.1.1"
clap = "2.33.3"
hex = "0.4.3"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_warn"] }
slog-term = "2.8.0"
slog-async = "2.6.0"

[dependencies.tokio]
version = "1.3.0"
features = ["full"]

[profile.dev]
lto = true
opt-level = "z"
codegen-units = 1
debug = false

[profile.dev.package."*"]
codegen-units = 1
opt-level = "z"
debug = false

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
debug = false

[profile.release.package."*"]
codegen-units = 1
opt-level = "s"
debug = false
