[package]
name = "codid"
publish = false
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cosmo-CoDiOS/codid"
description = "Rust implementation of the CoDi interface for Linux and Android based ROMs"
categories = ["cover-display", "codi"]
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
keywords = ["cover-display", "codi"]
edition = "2018"

[package.metadata.deb]
name = "codid"
maintainer = "Dom Rodriguez <shymega@shymega.org.uk>"
copyright = "2020-2021, Dom Rodriguez <shymega@shymega.org.uk>"
license-file = ["LICENSE", "0"]
extended-description = "This is a Rust implementation of the CoDi interface for Linux running on the Cosmo Communicator."
depends = "$auto"
section = "admin"
priority = "optional"
assets = [["README.md", "usr/share/doc/codid/README.md", "644"],
         ["target/release/codid", "usr/bin/codid", "755"],
         ["assets/config.sample.toml", "usr/share/doc/codid/config.sample.toml", "644"]]


[[bin]]
name = "codid"

[[bin]]
name = "codidctl"

[lib]
name = "codid"
path = "src/lib.rs"

[features]
default = []
term = []
journald = []

[dependencies]
glib = "0.10.3"
serialport = "4.0.1"
futures = "0.3.15"
dbus = "0.9.2"
config = "0.11.0"
dbus-tokio = "0.7.3"
restruct_derive = "0.1.1"
restruct = "0.1.1"
clap = "2.33.3"
slog-term = "2.8.0"
slog-async = "2.6.0"

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace"]

[dependencies.tokio]
version = "1.6.0"
features = ["full"]

[dependencies.txmodems]
git = "https://github.com/shymega/txmodems"
rev = "4e9ec0c0cc9c512da5b5f9133f51d30244096ce7"

[profile.dev]
lto = true
opt-level = "z"
codegen-units = 1
debug = true

[profile.dev.package."*"]
codegen-units = 1
opt-level = "z"
debug = true

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
debug = false

[profile.release.package."*"]
codegen-units = 1
opt-level = "s"
debug = false
