[package]
name = "codid"
publish = false
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cosmo-CoDiOS/codid"
description = "Rust implementation of the CoDi interface for Linux and Android based ROMs"
categories = ["aarch64", "daemon", "planet-computers"]
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
keywords = ["cover-display", "codi", "planet-computers"]
edition = "2018"

[[bin]]
name = "codid"

[[bin]]
name = "codictl"

[lib]
name = "codid"
path = "src/lib.rs"

[features]
default = []
stock-codi = ["codi_proto_common", "codi_stock_proto"]
codios-codi = ["codi_proto_common", "codi_os_proto"]
sailfish = ["dbus", "dbus-tokio"]
android = []
ubports = ["dbus", "dbus-tokio"]
gemian = ["dbus", "dbus-tokio"]
postmarketos = ["dbus", "dbus-tokio"]

[dependencies]
futures = "0.3.19"
config = "0.11.0"
clap = "3.0.10"
slog-term = "2.8.0"
slog-async = "2.7.0"

[dependencies.dbus]
version = "0.9.5"
optional = true

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace"]

[dependencies.tokio]
version = "1.15.0"
features = ["full"]

[dependencies.dbus-tokio]
version = "0.7.5"
optional = true

[dependencies.codi_os_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"
optional = true

[dependencies.codi_proto_common]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"
optional = true
features = ["std"]

[dependencies.codi_stock_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"
optional = true

[dependencies.codi_daemon_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"

[dependencies.codi_bootload_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"

[profile.dev]
lto = true
opt-level = "z"
codegen-units = 1
debug = true

[profile.dev.package."*"]
codegen-units = 1
opt-level = "z"
debug = true

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
debug = false

[profile.release.package."*"]
codegen-units = 1
opt-level = "s"
debug = false
