[package]
name = "codid"
publish = false
license = "MIT"
readme = "README.md"
repository = "https://github.com/Cosmo-CoDiOS/codid"
description = "Rust implementation of the CoDi interface for Linux and Android based ROMs"
categories = ["aarch64", "daemon", "planet-computers"]
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk>"]
keywords = ["cover-display", "codi", "planet-computers"]
edition = "2021"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/codid", dest = "/usr/bin/codid", mode = "755", config = false, doc = false },
    { source = "target/release/codictl", dest = "/usr/bin/codictl", mode = "755", config = false, doc = false },
    { source = "assets/lib/systemd/user/codid.service", dest = "/usr/lib/systemd/user/codid.service", config = true, doc = false }
]

[package.metadata.android]
package = "org.cosmocodios.codid.daemon"

build_targets = ["aarch64-linux-android"]

apk_name = "codidaemon"

[[bin]]
name = "codid"

[[bin]]
name = "codictl"

[lib]
name = "codid"
path = "src/lib.rs"

[features]
default = []
stock-codi = ["codi_proto_common", "codi_stock_proto"]
codios-codi = ["codi_proto_common", "codi_os_proto"]
sailfish = ["dbus", "ical"]
android = []
ubports = ["dbus", "ical"]
gemian = ["dbus", "ical"]
postmarketos = ["dbus", "ical"]
nixos = ["dbus", "ical"]

[dependencies]
futures = "0.3.21"
config = "0.13.1"
clap = "3.1.18"
slog-term = "2.9.0"
structure = "0.1.2"
lazy_static = "1.4.0"
jsonrpc-core = "18.0.0"
jsonrpc-ipc-server = "18.0.0"
jsonrpc-derive = "18.0.0"

[dependencies.dbus]
version = "0.9.5"
optional = true

[dependencies.ical]
version = "0.7.0"
optional = true

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace"]

[dependencies.tokio]
version = "1.19.0"
features = ["full"]

[dependencies.codi_os_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"
optional = true

[dependencies.codi_proto_common]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"
optional = true
features = ["std"]

[dependencies.codi_stock_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"
optional = true

[dependencies.codi_daemon_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"

[dependencies.codi_bootload_proto]
git = "https://github.com/Cosmo-CoDiOS/codi_protos"
branch = "main"

[profile.dev]
lto = true
opt-level = "z"
codegen-units = 1
debug = true
strip = false

[profile.dev.package."*"]
codegen-units = 1
opt-level = "z"
debug = true

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
debug = false
strip = true

[profile.release.package."*"]
codegen-units = 1
opt-level = "s"
debug = false
