[build.env]
passthrough = [
    "CARGO_TARGET_DIR"
]

[target.aarch64-unknown-linux-musl]
image = "shymega/rust-cross-custom:aarch64-unknown-linux-musl"

[target.aarch64-unknown-linux-gnu]
image = "shymega/rust-cross-custom:aarch64-unknown-linux-gnu"
