[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cosmo-codios/codios-build-containers:aarch64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cosmo-codios/codios-build-containers:x86_64-unknown-linux-musl"

[target.aarch64-linux-android]
image = "ghcr.io/cosmo-codios/codios-build-containers:aarch64-linux-android"
