[target.aarch64-unknown-linux-musl]
image = "shymega/rust-cross-custom:aarch64-unknown-linux-musl-0.2.1"

[target.aarch64-unknown-linux-gnu]
image = "shymega/rust-cross-custom:aarch64-unknown-linux-gnu-0.2.1"
