FROM rustembedded/cross:aarch64-unknown-linux-musl-0.2.1

RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && apt-get install -y libdbus-1-dev libdbus-1-dev:arm64 \
       pkg-config libglib2.0-dev libglib2.0-dev:arm64
