---
name: Nightly builder (Linux-based ROMs)

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-nightlies-linux:
    name: Nightly builds for ${{ matrix.rom }}/${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rom: [gemian, sailfishos, ubports, nixos, postmarketos, droidian]
        target: [aarch64-unknown-linux-musl, x86_64-unknown-linux-musl]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Cache Rust assets
        id: rust-cache
        uses: Swatinem/rust-cache@v2
      - name: Configure Rust
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          default: true
          components: llvm-tools-preview
          override: true
          target: ${{ matrix.target }}
          profile: minimal
      - name: Install Cross
        if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
        uses: brndnmtthws/rust-action-cargo-binstall@v1.0.0
        with:
          packages: cross
      - name: Build codid release for Linux-based ROMs.
        id: build-linux
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: >-
            --all --locked --verbose  --features=stock-codi,codios-codi,${{ matrix.rom
            }} --target=${{ matrix.target }}
          use-cross: true
      - name: Zip up the artifacts
        id: zipup
        if: ${{ steps.build-linux.outcome == 'success' }}
        run: zip ${{ github.workspace }}/codid-nightly-${{ matrix.rom }}-${{ matrix.target }}.zip ${{ github.workspace }}/target/${{ matrix.target }}/debug/codid ${{ github.workspace }}/target/${{ matrix.target }}/debug/codictl
      - name: Upload debug nightly build
        if: ${{ steps.zipup.outcome == 'success' }}
        uses: pyTooling/Actions/releaser@main
        with:
          tag: codid-nightly-${{ matrix.rom }}-${{ matrix.target }}
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: /github/workspace/codid-nightly-${{ matrix.rom }}-${{ matrix.target
            }}.zip
