name: codid CI debug builder
on:
    schedule:
        - cron: "0 0 */2 * *"
env:
    CARGO_TERM_COLOR: always
jobs:
    build-debug-linux:
        name: >-
            Debug builder for `codid` on the Cosmo Communicator. Target ROM: ${{ matrix.rom }}, and target CoDi variant: ${{ matrix.codi }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rom:
                    - gemian
                    - postmarketos
                    - ubports
                codi:
                    - stock-codi
                    - codios-codi
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Install Cross
              uses: actions-rs/install@v0.1
              with:
                  crate: cross
                  version: latest
                  use-tool-cache: false
            - name: Configure Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true
                  target: aarch64-unknown-linux-musl
                  profile: minimal
            - name: Build project in debug mode
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: >-
                      --all --locked --verbose  --features=${{ matrix.codi }},${{matrix.rom}} --target=aarch64-unknown-linux-musl
                  use-cross: true
            - name: Update nightly release
              uses: eine/tip@master
              with:
                  tag: nightly-${{ matrix.rom }}-${{ matrix.codi }}
                  rm: true
                  token: ${{ secrets.GITHUB_TOKEN }}
                  files: |
                      /home/runner/work/codid/codid/target/aarch64-unknown-linux-musl/debug/codid
                      /home/runner/work/codid/codid/target/aarch64-unknown-linux-musl/debug/codictl

    build-debug-android:
        name: >-
            Debug builder for the Android ROMs on Cosmo Communicator, compiled for both CoDi variants.
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Initialise Cargo binary caching, and install Cross
              uses: actions-rs/install@v0.1
              with:
                  crate: cross
                  version: latest
                  use-tool-cache: false
            - name: Configure Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true
                  target: aarch64-linux-android
                  profile: minimal
            - name: Build project in debug mode
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: >-
                      --all --locked --verbose  --features=stock-codi,codios-codi,android --target=aarch64-linux-android
                  use-cross: true
            - name: Update nightly release
              uses: eine/tip@master
              with:
                  tag: nightly-android-${{ matrix.codi }}
                  rm: true
                  token: ${{ secrets.GITHUB_TOKEN }}
                  files: |
                      /home/runner/work/codid/codid/target/aarch64-linux-android/debug/codid
                      /home/runner/work/codid/codid/target/aarch64-linux-android/debug/codictl
