name: Nightly Builders

on:
    workflow_dispatch:
    schedule:
        - cron: 0 0 * * *

concurrency:
    group: gh-ref-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-android-debug:
        uses: ./.github/workflows/ci-debug-builds-android.yml
        secrets: inherit

    build-linux-debug:
        uses: ./.github/workflows/ci-debug-builds-linux.yml
        secrets: inherit
