name: codid CI debug builder
'on':
  - push
  - pull_request
env:
  CARGO_TERM_COLOR: always
jobs:
  build-debug:
    name: >-
      Debug builder for Cosmo ROM: ${{ matrix.rom }}, CoDi firmware: ${{
      matrix.codi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rom:
          - android
          - gemian
          - postmarketos
          - sailfish
          - ubports
        codi:
          - stock-codi
          - codios-codi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install musl tools
        run: sudo apt-get install -y musl-tools
      - name: Setup Cargo binary caching/installation action
        uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest
          use-tool-cache: true
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: aarch64-unknown-linux-musl
          profile: minimal
      - name: Build project (musl/aarch64) in debug mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: >-
            --all --locked --verbose  --features=${{ matrix.codi
            }},${{matrix.rom}} --target=aarch64-unknown-linux-musl
          use-cross: true
      - name: Upload [debug] artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'codid-${{ matrix.rom }}-${{ matrix.codi }}-debug'
          path: |
            /home/runner/work/codid/codid/target/aarch64-unknown-linux-musl/debug/codid
            /home/runner/work/codid/codid/target/aarch64-unknown-linux-musl/debug/codictl