name: codid CI release builder
'on': push
env:
  CARGO_TERM_COLOR: always
jobs:
  create-release:
  #  if: startsWith(github.ref, 'refs/tags/')
    name: >-
      Release builder for Cosmo ROM: ${{ matrix.rom }}, CoDi firmware: ${{
      matrix.codi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rom:
          - android
          - gemian
          - postmarketos
          - sailfish
          - ubports
        codi:
          - stock-codi
          - codios-codi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install musl tools
        run: sudo apt-get install -y musl-tools
      - name: Install cargo-cross
        uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest
          use-tool-cache: true
      - name: Install cargo-binutils
        uses: actions-rs/install@v0.1
        with:
            crate: cargo-binutils
            version: latest
            use-tool-cache: true
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: llvm-tools-preview
          override: true
          target: aarch64-unknown-linux-musl
          profile: minimal
      - name: Build project (musl/aarch64) in release mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: >-
            --all --release --locked --verbose  --features=${{ matrix.codi
            }},${{matrix.rom}} --target=aarch64-unknown-linux-musl
          use-cross: true
      - name: Strip the CoDiOS image if the build is a release
        run: cargo strip --release --bin codid && cargo strip --release --bin codictl
      - name: Package Release
        shell: bash
        run: |
            tar -czvf /home/runner/work/codid/codid-${{matrix.rom}}-${{matrix.codi}}-release.tgz /home/runner/work/codid/codid/target/aarch64-unknown-linux-musl/debug/codid /home/runner/work/codid/codid/target/aarch64-unknown-linux-musl/debug/codictl
      - name: Publish release artifacts
        uses: softprops/action-gh-release@v1
        with:
            files: /home/runner/work/codid/codid-${{ matrix.rom }}-${{ matrix.codi }}-release.tgz
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
