---
name: CI Tests

on:
  push:
    paths: ["src/", "Cargo.toml", "Cargo.lock", "rust-toolchain"]
  workflow_dispatch:

jobs:
  test-android:
    uses: ./.github/workflows/ci-tests-android.yml
    secrets: inherit

  test-linux:
    uses: ./.github/workflows/ci-tests-linux.yml
    secrets: inherit

  test-nix:
    uses: ./.github/workflows/ci-tests-nix.yml
    secrets: inherit
