name: CI test workflow
on:
    push:
    workflow_dispatch:
    pull_request:
env:
    CARGO_TERM_COLOR: always
jobs:
    tests:
        name: Run tests on various Rust channels, and the supported targets
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - aarch64-unknown-linux-musl
                    - aarch64-linux-android
                channel:
                    - stable
                rom:
                    - gemian
                    - postmarketos
                    - ubports
                    - android
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Configure Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.channel }}
                  profile: minimal
                  components: clippy
                  override: true
                  target: ${{ matrix.target }}
                  default: true
            - name: Install Cross
              uses: actions-rs/install@v0.1
              with:
                  crate: cross
                  version: latest
                  use-tool-cache: true
            - name: Run build of project
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --features=${{ matrix.rom }},stock-codi,codios-codi --target=${{ matrix.target }}
                  use-cross: true
            - name: Run tests on project
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --features=${{ matrix.rom }},stock-codi,codios-codi --target=${{ matrix.target }}
                  use-cross: true
            - name: Run Clippy checks on project
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --features=${{ matrix.rom }},stock-codi,codios-codi --target=${{ matrix.target }}
                  use-cross: true
