name: codid CI tests
'on':
  - push
  - pull_request
env:
  CARGO_TERM_COLOR: always
jobs:
  tests:
    name: Run tests on all Rust channels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - stable
          - beta
          - nightly
        include:
          - build: beta
            rust: beta
          - build: nightly
            rust: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '${{ matrix.rust || ''stable'' }}'
          profile: minimal
          components: clippy
          override: true
          target: x86_64-unknown-linux-musl
          default: true
      - name: Setup Cargo binary caching/installation action
        uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest
          use-tool-cache: true
      - name: Build debug codid/codictl
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: '--all-features --target=x86_64-unknown-linux-musl'
          use-cross: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: '--all-features --target=x86_64-unknown-linux-musl'
          use-cross: true
      - name: Run Clippy checks
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: clippy
          args: '--all-features --target=x86_64-unknown-linux-musl'
