name: CI test workflow

on:
    push:
    workflow_dispatch:
    pull_request:
env:
    CARGO_TERM_COLOR: always
jobs:
    tests:
        name: Run tests on various Rust channels, and the supported targets
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - aarch64-unknown-linux-musl
                    - x86_64-unknown-linux-musl
                    - aarch64-linux-android
                channel:
                    - stable
                    - beta
                    - nightly
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Configure Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.channel }}
                  profile: minimal
                  components: clippy
                  override: true
                  target: ${{ matrix.target }}
                  default: true
            - name: Install Cross
              uses: actions-rs/install@v0.1
              with:
                  crate: cross
                  version: latest
                  use-tool-cache: false
            - name: Install native deps
              run: sudo apt-get install -y libdbus-1-dev:arm64 pkg-config:arm64 libudev-dev:arm64 libglib2.0-dev:arm64 libudev-dev:amd64 musl-dev:arm64 libdbus-1-dev:amd64 libsqlite3-dev:arm64 libsqlite3-dev:amd64 cmake:amd64
            - name: Run build of project
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --all-features --target=${{ matrix.target }}
                  use-cross: true
            - name: Run tests on project
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --all-features --target=${{ matrix.target }}
                  use-cross: true
            - name: Run Clippy checks on project
              uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --all-features --target=${{ matrix.target }}
                  use-cross: true
