name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./rust

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
        include:
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: target/aarch64-unknown-linux-musl/release/codi-linuxd
            release_name: cosmo-aarch64-musl
            cross: true
            strip: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: target/aarch64-unknown-linux-gnu/release/codi-linuxd
            release_name: cosmo-aarch64-gnu
            cross: true
            strip: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-11-08
          target: ${{ matrix.target }}
      
      - name: Build project
        uses: marcopolo/cargo@master
        with:
          command: build
          args: --release --locked --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}
          working-directory: ./rust

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.release_name }}
          path: ./rust/${{ matrix.artifact_name }}

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file: ./rust/${{ matrix.artifact_name }}
          args: --lzma
          strip: ${{ matrix.strip }}

      - name: Create release 
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./rust/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
